// Using uuid module temporarily to generate unique IDs
// Future versions should use ID generated by mongodb
// uuid/v1 is a timestamp-based uuid
const uuidv1 = require('uuid/v1');

export const addQuestion = (question) => ({
    type: 'ADD_QUESTION',
    id: uuidv1(),
    question
});

export const editQuestion = (id, updates) => ({
    type: 'EDIT_QUESTION',
    id,
    updates
});

export const removeQuestion = (id) => ({
    type: 'REMOVE_QUESTION',
    id
});